### ISSUE TITLE
AASX File validation throws an invalid error

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-test-engines#35]
An any AASX File in case of file validation throws "Relationship has non-existing target aasx\aasx-origin" error.

The file used for testing:
[test_correct.zip](https://github.com/user-attachments/files/16267144/test_correct.zip)

Ideally this file has no errors. Still the test-engine gives below result:

![image](https://github.com/user-attachments/assets/0d1a1215-0b42-438e-a4b5-7eb3f7fb4631)

**Comment by otto-ifak** [comment]
In the zip file, there is missing a file `aasx/aasx-origin` which should exist according to the OPC spec.
As multiple people have already reported this to me, should we better add a warning about this?

**Comment by juileetikekar** [comment]
Hi @otto-ifak , the aasx/origin is present and the file as well.

<img width="836" alt="image" src="https://github.com/user-attachments/assets/21308311-242a-434f-858f-bf848df547dc">

I also tested the file with other validation tools where it worked fine.

**Comment by fscheren22** [comment]
Hi, we also get the same error by generating aasx files through our engine. Is there any new information about this topic? Any solution? 
Best regards Frank

**Comment by otto-ifak** [comment]
python -c "import os; import aas_test_engines;  print(os.path.abspath(aas_test_engines.__file__))"

**Comment by otto-ifak** [comment]
@fscheren22 Thanks to @juileetikekar we found the origin of this bug: Filenames in zip archives are unix-like file names so that the code runs fine on unix systems like mine. On Windows, however, the exact same file fails as in your case.

Could you please check, if this fixes the validation on your system? (You need to check out the `improve_api_tests` branch though)

**Comment by RALewin** [comment]
@otto-ifak 
Hi there!
Currently we get the following Errors, when exchanging the aas_test_engines folder with the one from "improve_api_tests":

`Traceback (most recent call last):
  File "C:\Users\(Username)\PycharmProjects\Asset Administration Shell\main.py", line 1, in <module>
    from aas_test_engines import file
  File "C:\Users\(Username)\PycharmProjects\Asset Administration Shell\.venv\Lib\site-packages\aas_test_engines\file.py", line 14, in <module>
    from ._file.generate import generate_graph, FlowGraph
  File "C:\Users\(Username)\PycharmProjects\Asset Administration Shell\.venv\Lib\site-packages\aas_test_engines\_file\generate.py", line 1, in <module>
    from fences.json_schema.normalize import normalize, NormalizationConfig
ImportError: cannot import name 'NormalizationConfig' from 'fences.json_schema.normalize' (C:\Users\(Username)\PycharmProjects\Asset Administration Shell\.venv\Lib\site-packages\fences\json_schema\normalize.py)`

**Comment by otto-ifak** [comment]
@RALewin thanks for the response, seems to be a dependency problem. Maybe you can wait until the next release of the python package? This way you do not need to fiddle with the dependencies yourself.

@juileetikekar Is your aasx file working now?

**Comment by juileetikekar** [comment]
Hi @otto-ifak ,

The issue is fixed now on my end. Thanks for the fix and update.

**Comment by MarioFromTheFH** [comment]
We are facing a similar issue right now and can't figure out what's the issue. 

@juileetikekar - what did you change?
