### ISSUE TITLE
Version 0.5.0 Bug

### ISSUE THREAD

**Issue by RALewin** [admin-shell-io/aas-test-engines#61]
Hi,
We added the new Version to our Project and now we get the following error Traceback:

Traceback (most recent call last):
  File "c:\Users\[User]\Desktop\AASX Validator\from aas_test_engines import file.py", line 1, in <module>
    from aas_test_engines import file
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python312\Lib\site-packages\aas_test_engines\file.py", line 14, in <module>
    from ._file.generate import generate_graph, FlowGraph
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python312\Lib\site-packages\aas_test_engines\_file\generate.py", line 1, in <module>
    from fences.json_schema.normalize import normalize, NormalizationConfig
ImportError: cannot import name 'NormalizationConfig' from 'fences.json_schema.normalize' (C:\Users\[User]\AppData\Local\Programs\Python\Python312\Lib\site-packages\fences\json_schema\normalize.py)

**Comment by otto-ifak** [comment]
Hi @RALewin , have you added the project via `pip install` or simply cloned the git repo?

**Comment by otto-ifak** [comment]
Closed due to inactivity, feel free to re-open if necessary
