### ISSUE TITLE
API Validation crashes (Submodel Repository Service)

### ISSUE THREAD

**Issue by pjaydev** [admin-shell-io/aas-test-engines#80]
With our API, the validation crashes with the following output:

```
> aas_test_engines check_server http://localhost:4102/api/v1 https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python\python3_11_6\Scripts\aas_test_engines.exe\__main__.py", line 7, in <module>
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\__main__.py", line 163, in main
    commands[command](remaining_args)
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\__main__.py", line 111, in run_api_test
    result, mat = api.execute_tests(exec_conf, suite, args.version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\api.py", line 23, in execute_tests
    return v3_0.execute_tests(conf, suite)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\test_cases\v3_0\api.py", line 1699, in execute_tests
    sub_mat = test_suite.execute()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\test_cases\v3_0\api.py", line 574, in execute
    self.execute_semantic_tests()
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\test_cases\v3_0\api.py", line 565, in execute_semantic_tests
    test_fn()
  File "C:\python\python3_11_6\Lib\site-packages\aas_test_engines\test_cases\v3_0\api.py", line 1460, in test_include_concept_descriptions
    _assert('conceptDescriptions' in data, 'contains conceptDescriptions', Level.WARNING)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

it started going well so far, I could successfully use the validation to detect and fix several bugs in our API and received usable results. 
But after fixing the most recently detected bug, I am no longer able to use the validator and just receiving this error instead.

**Comment by Frosty2500** [comment]
I also had the same issue, https://github.com/admin-shell-io/aas-test-engines/issues/78 here you can see how I was able to get it working for now.

**Comment by otto-ifak** [comment]
@pjaydev thanks for reporting. This is indeed a duplicate of #78 and fixed now.
